spring.application.name=aws_final
server.port=8081

### DATABASE CONNECTION
# Connecting to Docker MySQL mapped to port 3307
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3307/finalProject?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:Viper-1018@@FELIPE2}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

### HIKARI POOL (HORIZONTAL SCALING READY)
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.max-lifetime=1800000

### JPA / HIBERNATE BLINDADO
spring.sql.init.mode=${SQL_INIT_MODE:never}
spring.jpa.hibernate.ddl-auto=${DDL_AUTO:update}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false


### LOGGING & SECURITY
logging.level.org.springframework.security=DEBUG
# logging.level.org.hibernate.SQL=DEBUG
app.jwt.secret=${JWT_SECRET:F3l1p3_esta_es_una_llave_secreta_muy_larga_y_segura_de_al_menos_256_bits}
app.jwt.expiration=3600000

### AWS S3 CONFIG
# El nombre que le vayas a poner a tu bucket en AWS
aws.s3.bucket=${S3_BUCKET_NAME:mi-ticket-MercadoLocal}
# La region por defecto
aws.region=${AWS_REGION:us-east-1}
